package apimart_suno

var ModelList = []string{
	"suno-music",
	"suno-lyrics",
	"suno-aligned-lyrics",
	"suno-bpm",
	"suno-concat",
	"suno-generate-video",
	"suno-persona",
	"suno-upload",
	"suno-upsample-tags",
	"suno-crop",
	"suno-fade-in",
	"suno-fade-out",
	"suno-remove-section",
	"suno-sounds",
	"suno-create-voice",
	"suno-adjust-speed",
	"suno-add-instrumental",
	"suno-add-stem",
	"suno-add-vocals",
	"suno-cover",
	"suno-extend",
	"suno-mashup",
	"suno-midi",
	"suno-remaster",
	"suno-replace-section",
	"suno-sample",
	"suno-inspo",
	"suno-stems",
	"suno-stems-all",
	// V6 新增
	"suno-download",
	"suno-upload-cover",
	"suno-upload-extend",
	"suno-create-model",
}

var ChannelName = "apimart-suno"
